"""add sessions

Revision ID: 3ea79f56abca
Revises: b3485588290c
Create Date: 2025-06-07 19:36:45.977700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea79f56abca'
down_revision: Union[str, None] = 'b3485588290c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklisted_tokens', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('blacklisted_tokens', sa.Column('reason', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_blacklisted_tokens_user_id'), 'blacklisted_tokens', ['user_id'], unique=False)
    op.add_column('users', sa.Column('password_reset_code', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_reset_attempts', sa.Integer(), nullable=False, server_default='0')) # manually edited, add default
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0')) # manually edited, add default
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_attempt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'last_login_attempt')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'password_reset_attempts')
    op.drop_column('users', 'password_reset_expires_at')
    op.drop_column('users', 'password_reset_code')
    op.drop_index(op.f('ix_blacklisted_tokens_user_id'), table_name='blacklisted_tokens')
    op.drop_column('blacklisted_tokens', 'reason')
    op.drop_column('blacklisted_tokens', 'user_id')
    # ### end Alembic commands ###
